### ISSUE TITLE
Broken on v0.11.0

### ISSUE THREAD

**Issue by codenothing** [mattinsler/longjohn#12]
Getting an error at the end of a program when using longjohn (0.2.0):

```js
require( 'longjohn' );

console.log( 'Start' );
setTimeout(function(){
	console.log( 'Timeout' );
}, 1000);
```

```
corey@corey-mac:~/git/lj$ node test.js
Start
Timeout

/Users/corey/git/lj/node_modules/longjohn/dist/longjohn.js:181
        throw e;
              ^
TypeError: Function.prototype.apply: Arguments list has wrong type
    at Function.prepareStackTrace (/Users/corey/git/lj/node_modules/longjohn/dist/longjohn.js:123:48)
    at new Error (<anonymous>)
    at wrap_callback (/Users/corey/git/lj/node_modules/longjohn/dist/longjohn.js:167:19)
    at process.nextTick (/Users/corey/git/lj/node_modules/longjohn/dist/longjohn.js:257:15)
    at onwrite (_stream_writable.js:249:15)
    at WritableState.onwrite (_stream_writable.js:92:5)
    at WriteStream.Socket._write (net.js:634:5)
    at doWrite (_stream_writable.js:211:10)
    at writeOrBuffer (_stream_writable.js:201:5)
    at WriteStream.Writable.write (_stream_writable.js:172:11)
```

**Comment by tvervest** [comment]
Any news on this issue (or the PR?). I'm having the same problem and I'm sure I'm not the only one ;) It would be great if we could manage to get a PR (without failing tests ;)) merged into the project.

**Comment by mattinsler** [comment]
Fixed by PR.
