### ISSUE TITLE
No long stacktrace printed on ECONNRESET

### ISSUE THREAD

**Issue by binarykitchen** [mattinsler/longjohn#31]
```
^C
/home/michael.heuberger/binarykitchen/code/videomail.io/node_modules/longjohn/dist/longjohn.js:185
        throw e;
              ^
Error: read ECONNRESET
  at errnoException (net.js:904:11)
  at Pipe.onread (net.js:558:19)
```

Why isn't longjohn printing a long stack trace here with all the callbacks?

I placed `require('longjohn');` on the top of my gulp file ...

**Comment by kopertop** [comment]
I'm having a similar issue. I downloaded longjohn specifically to try to debug this error, but it gets stuck somewhere and won't print out a full stack trace:

```
Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TLSWrap.onread (net.js:544:26)
---------------------------------------------
    at fireErrorCallbacks (net.js:444:15)
    at TLSSocket.Socket._destroy (net.js:480:3)
    at TLSWrap.onread (net.js:544:17)
```

Running node 4.4.3 on AWS Lambda.
