### ISSUE TITLE
Invalid Array length error with 0.2.6

### ISSUE THREAD

**Issue by pinnamur** [mattinsler/longjohn#45]
We have a series of node modules that depend on latest version of longjohn (which currently points to 0.2.6). Our node modules are distributed to our customers and longjohn@0.2.6 errors out with 

RangeError: Invalid array length
    at onwrite (_stream_writable.js:266:15)
    at WritableState.onwrite (_stream_writable.js:97:5)
    at Socket._write (net.js:654:5)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at Writable.write (_stream_writable.js:183:11)
    at Socket.write (net.js:616:40)
    at Console.log (console.js:54:16)

We narrowed down the problem with longjohn@0.2.6 module, and published PR. It would be great if you can include the fix for this and publish a new version.

**Comment by pinnamur** [comment]
Here is the PR https://github.com/mattinsler/longjohn/pull/44

**Comment by mattinsler** [comment]
Published as 0.2.7.
