### ISSUE TITLE
Doesn't work with promises

### ISSUE THREAD

**Issue by dypsilon** [mattinsler/longjohn#63]
All I get is:
```
    at Promise.resolve.then (/usr/src/app/lib/promises/index.js:61:15)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```
Is this project still alive?

**Comment by tenaciousRas** [comment]
Can you test against a new fork at https://github.com/drauggres/longjohn ?

**Comment by mike442144** [comment]
@tenaciousRas I tried both your repo and this one. But I couldn't get what I want, it seems nothing happened. Does it support node-v6.9.1 LTS?

**Comment by tenaciousRas** [comment]
Same here.  I think you meant @drauggres repo?  I only referred to @drauggres because it was ahead of this fork.  I couldn't get either fork to work with my NJS v5 project when I wrote that comment in late Oct/2016.

**Comment by mike442144** [comment]
I see, thanks.

**Comment by Siilwyn** [comment]
The `--trace-warnings` flag is as close as I can get without this module. :/
